spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: moovium
  main:
    banner-mode: off
  datasource:
    url: ${ENV_URL_DATABASE}
    username: ${ENV_USERNAME}
    password: ${ENV_PASSWORD}
  flyway:
    clean-disabled: false
    locations: classpath:db/migration,classpath:db/testdata
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${ID_CLIENT}
            client-secret: ${CLIENT_SECRET}
