spring:
  application:
    name: moovium
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  config:
    import: optional:classpath:.env[.properties]
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  datasource:
    url: ${ENV_URL_DATABASE}
    username: ${ENV_USERNAME}
    password: ${ENV_PASSWORD}
  threads:
    virtual:
      enabled: true
  flyway:
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID_CLIENT}
            client-secret: ${GOOGLE_CLIENT_SECRET}

banned:
  words:
    location: classpath:config/banned_words.txt
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  override-with-generic-response: false

---
# DEVELOPMENT PROFILE
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    clean-disabled: false
    locations: classpath:db/migration,classpath:db/testdata

dev:
  database:
    clean-on-shutdown: true

logging:
  level:
    com.thomazllr.moovium: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'

